    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 'Fantasía', 'Salamandra', '5');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 'Realismo mágico', 'Diana', '8');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('El Señor de los Anillos: La Comunidad del Anillo', 'J.R.R. Tolkien', 'Fantasía', 'Minotauro', '6');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Orgullo y prejuicio', 'Jane Austen', 'Romance', 'Alba', '4');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('1984', 'George Orwell', 'Ciencia ficción', 'Debolsillo', '7');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('El Principito', 'Antoine de Saint-Exupéry', 'Fábula', 'Salamandra', '9');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('El código Da Vinci', 'Dan Brown', 'Misterio', 'Planeta', '3');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Matar a un ruiseñor', 'Harper Lee', 'Drama', 'Zeta Bolsillo', '5');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('El Hobbit', 'J.R.R. Tolkien', 'Fantasía', 'Minotauro', '4');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Los juegos del hambre', 'Suzanne Collins', 'Distopía', 'RBA Molino', '6');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Crimen y castigo', 'Fiodor Dostoievski', 'Ficción', 'Alianza Editorial', '8');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('El Alquimista', 'Paulo Coelho', 'Autoayuda', 'HarperOne', '7');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Las aventuras de Tom Sawyer', 'Mark Twain', 'Aventura', 'Penguin Clásicos', '5');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('El nombre del viento', 'Patrick Rothfuss', 'Fantasía', 'Plaza & Janés', '6');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('La sombra del viento', 'Carlos Ruiz Zafón', 'Misterio', 'Planeta', '7');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Frankenstein', 'Mary Shelley', 'Terror', 'Penguin Clásicos', '4');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 'Novela', 'Alfaguara', '5');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Las Crónicas de Narnia: El león, la bruja y el ropero', 'C.S. Lewis', 'Fantasía', 'Destino', '6');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Los Pilares de la Tierra', 'Ken Follett', 'Histórica', 'Debolsillo', '7');
    INSERT INTO libro (titulo, autor, tipo, editorial, ejemplares) VALUES ('Drácula', 'Bram Stoker', 'Terror', 'Edimat Libros', '5');
    
    

    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Gómez Rodríguez', 'Ana', 'Calle Mayor 10', 'Dos Hermanas', '41700');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('López Martínez', 'Pedro', 'Avenida Valencia 45', 'Alcalá de Guadaíra', '41500');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Fernández García', 'María', 'Plaza del Sol 7', 'Mairena del Aljarafe', '41927');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Martínez López', 'Carlos', 'Calle San Juan 15', 'Utrera', '41710');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('González Rodríguez', 'Laura', 'Calle Mayor 30', 'Écija', '41400');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Rodríguez García', 'Manuel', 'Avenida Gran Vía 100', 'Los Palacios y Villafranca', '41720');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Pérez Martínez', 'Isabel', 'Plaza Mayor 12', 'Carmona', '41410');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Sánchez Fernández', 'Javier', 'Calle Valencia 5', 'Marchena', '41620');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Hernández Gómez', 'Sara', 'Calle Real 3', 'Coria del Río', '41100');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Ramírez López', 'Antonio', 'Avenida del Mar 20', 'Arahal', '41600');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Torres García', 'Elena', 'Plaza España 25', 'Osuna', '41640');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Díaz Martínez', 'Miguel', 'Calle Granada 8', 'La Rinconada', '41309');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Morales Rodríguez', 'Luis', 'Calle Mayor 17', 'El Viso del Alcor', '41520');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Vargas López', 'Carmen', 'Avenida del Mar 30', 'Estepa', '41560');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Jiménez Fernández', 'Rosa', 'Plaza del Sol 5', 'Gines', '41960');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Ruiz Martínez', 'Juan', 'Calle Gran Vía 50', 'San Juan de Aznalfarache', '41920');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Ortega García', 'Lucía', 'Calle Valencia 10', 'Tomares', '41940');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Fuentes López', 'Andrés', 'Avenida de la Libertad 12', 'Castilleja de la Cuesta', '41950');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Soto Fernández', 'Paula', 'Plaza Mayor 8', 'Bormujos', '41930');
    INSERT INTO usuario (apellidos, nombre, direccion, poblacion, codigo) VALUES ('Herrera Martínez', 'Diego', 'Calle Granada 3', 'Espartinas', '41807');
